name: "Publish Extension"

on:
  release:
    types: ["released"]


jobs:
  publish-cws:
    runs-on: ubuntu-latest
    env:
      EXTENSION_ID: ${{ vars.EXTENSION_ID }}
      PUBLISHER_ID: ${{ vars.PUBLISHER_ID }}
      CLIENT_ID: ${{ vars.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
      ASSET_FILENAME: "buff-leo-${{ github.event.release.tag_name }}.zip"

    steps:
      - name: "Install Node.js"
        uses: actions/setup-node@v7
        with:
          node-version: 22
      
      - name: "Upgrade NPM"
        run: npm install --global npm@latest && npm --version
      
      - name: "Install CLI tool"
        run: npm install --global --min-release-age=14 chrome-webstore-upload-cli

      - name: "Download release asset"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release download ${{ github.event.release.tag_name }} --repo ${{ github.repository }} --pattern $ASSET_FILENAME

      - name: "Publish extension"
        run: chrome-webstore-upload --source $ASSET_FILENAME
